--- 
artifacts: 
  base-directory: publish*
  files: 
    - "**/*"
phases: 
  build: 
    commands: 
      - "dotnet restore"
      - "dotnet test dataservice.tests"
      - "dotnet publish -o ./publish"
  install: 
    runtime-versions: 
      dotnet: 3.0
version: 0.2
